let nombre= "Pedro";
let apellido= "Gonzales";
console.log(nombre + " " + apellido);
let numberone=120;
let numbertwo=20;
let resultsuma = numberone + numbertwo;
let resultresta = numberone - numbertwo;
let resultmulti = numberone * numbertwo;
let resultdivision = numberone / numbertwo;
console.log("suma:" , resultsuma);
console.log("resta:" , resultresta);
console.log("multiplicacion:", resultmulti);
console.log("division:", resultdivision);
let comp = numberone > numbertwo;
console.log(comp);
let numberthree = resultsuma + 720;
console.log("suma-variable+numero:" ,numberthree);